### ISSUE TITLE
Differences with the original implementation

### ISSUE THREAD

**Issue by lucabergamini** [ReidWilliams/autoencoder-vaegan#1]
Hi, could you give me some insight on the differences between your code and the original implementation? In particular:
* The discriminator network has a more complex structure than the original one (1024 filters for examples)
* You're not training the decoder (generator) using an alpha multiplier
* There is no sign of the encoder network at all, together with the reparam trick

Are these choices intended?

**Comment by ReidWilliams** [comment]
Hi @lucabergamini 

Sorry, the repo is due for a name change. I started the project with the intent of exploring the VAEGAN paper, but over time shifted to just exploring GANs, that's why there's no encoder. That's also why the discriminator architecture is not true to the VAEGAN paper. Both the generator and discriminator networks are based on the DCGAN-tensorflow repo.
